Repository refinery-platform/refinery-platform, pull requests merged in 2018-09, with the labels that each got.

#2984 Scottx611x/add test coverage for refinery import tasks
  refinery/analysis_manager/tasks.py
  refinery/core/models.py
  refinery/core/tests.py
  refinery/tool_manager/tests.py
Labels: review

#2990 Render vis-tool-user-not-allowed template with a 403 status
  refinery/tool_manager/tests.py
  refinery/tool_manager/views.py
Labels: review

#2985 Trim Tool's creation date in `display_name` to the second
  refinery/tool_manager/models.py
  refinery/tool_manager/tests.py
  refinery/tool_manager/utils.py
  refinery/tool_manager/views.py
Labels: review

#2991 Scottx611x/tool manager views cleanup
  refinery/tool_manager/tests.py
  refinery/tool_manager/urls.py
  refinery/tool_manager/views.py
  refinery/ui/source/js/commons/services/tool-definitions.js
  refinery/ui/source/js/commons/services/tool-definitions.spec.js
  refinery/ui/source/js/tool-launch/directives/tool-select.spec.js
  refinery/ui/source/js/tool-launch/services/tool-select-service.js
Labels: review

#2997 Jkmarx/cell edit
  refinery/ui/source/js/file-browser/ctrls/ctrl.js
  refinery/ui/source/js/file-browser/partials/assay-files.html
  refinery/ui/source/js/file-browser/services/factory.js
Labels: review

#3005 Hackdna/rewrite import file
  refinery/analysis_manager/tasks.py
  refinery/config/settings/base.py
  refinery/core/models.py
  refinery/core/tasks.py
  refinery/core/tests.py
  refinery/data_set_manager/models.py
  refinery/data_set_manager/single_file_column_parser.py
  refinery/data_set_manager/tasks.py
  refinery/data_set_manager/test_views.py
  refinery/data_set_manager/tests.py
  refinery/data_set_manager/views.py
  refinery/file_store/models.py
  refinery/file_store/tasks.py
  refinery/file_store/test_models.py
  refinery/file_store/test_tasks.py
  refinery/file_store/test_utils.py
  refinery/file_store/utils.py
Labels: files, fix-8x-large, import, server

#3009 Data set manager utils cleanup
  refinery/data_set_manager/utils.py
Labels: dataset, fix-2x-small, server, technical debt

#3013 Delete static and upload file buckets even if not empty
  deployment/terraform/modules/s3/main.tf
Labels: aws, deployment, enhancement, fix-1x-quick

#3014 Hackdna/core tasks cleanup
  refinery/core/tasks.py
Labels: celery, core, fix-1x-quick, server, technical debt

#3015 Hackdna/data set manager tasks cleanup
  refinery/data_set_manager/tasks.py
Labels: dataset, fix-1x-quick, server, technical debt

#3019 Add soft time limit for Celery tasks
  refinery/config/settings/base.py
  refinery/file_store/tasks.py
Labels: celery, files, fix-2x-small, server

#3021 Add error handling when saving files directly to S3
  refinery/data_set_manager/isa_tab_parser.py
Labels: aws, bug, files, fix-1x-quick, import, server

#3022 Fix for tabular metadata file import to S3 failure
  refinery/file_store/tasks.py
Labels: aws, files, fix-2x-small, import, important, server

#3030 Update get_file_size() to support S3 storage backend
  refinery/core/models.py
  refinery/file_store/models.py
Labels: aws, enhancement, files, fix-2x-small, server

#3033 Update get_datafile_url()
  refinery/file_store/models.py
Labels: aws, enhancement, files, fix-2x-small, security

#3036 Remove is_local()
  refinery/core/models.py
  refinery/core/tests.py
  refinery/data_set_manager/models.py
  refinery/factory_boy/utils.py
  refinery/file_store/models.py
  refinery/tool_manager/models.py
Labels: aws, enhancement, files, fix-4x-medium, server

#3038 Remove get_absolute_path()
  refinery/data_set_manager/models.py
  refinery/data_set_manager/tasks.py
  refinery/file_store/management/__init__.py
  refinery/file_store/management/commands/__init__.py
  refinery/file_store/management/commands/get_filestore_size.py
  refinery/file_store/models.py
Labels: aws, enhancement, files, server
