Repository refinery-platform/refinery-platform, pull requests merged in 2018-08, with the labels that each got.

#2928 Remove unused modules from requirements.txt
  requirements.txt
Labels: deployment, fix-1x-quick, security, server, technical debt

#2932 Jkmarx/remove projects template
  refinery/config/urls.py
  refinery/core/api.py
  refinery/core/forms.py
  refinery/core/urls.py
  refinery/core/views.py
  refinery/templates/core/project.html
  refinery/templates/core/project_edit.html
  refinery/templates/core/project_new.html
  refinery/ui/source/js/commons/services/projects.js
  refinery/ui/source/js/dashboard/controllers/dashboard.js
  refinery/ui/source/js/dashboard/views/launch-pad.html
Labels: technical debt

#2975 Avoid adding UUIDs of FileStoreItems that have already been imported
  refinery/analysis_manager/tasks.py
Labels: review

#2976 Scottx611x/fix refinery import pending state all local inputs
  refinery/analysis_manager/models.py
  refinery/core/models.py
  refinery/core/tests.py
Labels: review
