Repository refinery-platform/refinery-platform, pull requests merged in 2018-05, with the labels that each got.

#2737 Add basic functionality for creating S3 user data object keys
  refinery/file_store/migrations/0001_initial.py
  refinery/file_store/migrations/0004_auto_20171117_1420.py
  refinery/file_store/models.py
  refinery/file_store/tasks.py
  refinery/file_store/test_models.py
  refinery/file_store/test_utils.py
  refinery/file_store/utils.py
Labels: cloud, feature, files, fix-4x-medium, server

#2748 Switch network adapter type to paravirtualized for increased performance
  Vagrantfile
Labels: deployment, fix-1x-quick, performance, server

#2761 Hot-fix: Fix relaunch bug.
  refinery/ui/source/js/data-set-visualization/ctrls/visualization-ctrl.js
  refinery/ui/source/js/data-set-visualization/partials/visualization.html
Labels: bug

#2793 Streamline private network adapter config
  Vagrantfile
Labels: deployment, enhancement, performance, server
