Repository refinery-platform/refinery-platform, pull requests merged in 2018-07, with the labels that each got.

#2843 Fix styling for width and padding in analysis group.
  refinery/ui/source/js/file-browser/services/factory.js
  refinery/ui/source/js/file-browser/services/factory.spec.js
Labels: enhancement

#2811 Scottx611x/metadata revisions
  refinery/core/models.py
  refinery/core/tests.py
  refinery/data_set_manager/models.py
  refinery/data_set_manager/search_indexes.py
  refinery/data_set_manager/single_file_column_parser.py
  refinery/data_set_manager/tasks.py
  refinery/data_set_manager/test-data/rfc-test-local-edited.zip
  refinery/data_set_manager/test-data/rfc-test-local.zip
  refinery/data_set_manager/test-data/single-file/test1.txt
  refinery/data_set_manager/test-data/single-file/test2.txt
  refinery/data_set_manager/test-data/single-file/three-line-local.csv
  refinery/data_set_manager/tests.py
  refinery/data_set_manager/views.py
  refinery/file_store/models.py
  refinery/file_store/test_models.py
  refinery/templates/data_set_manager/import.html
  refinery/ui/source/js/data-set-about/partials/details.html
  refinery/ui/source/js/data-set-import/controllers/input-confirmation-modal-ctrl.js
  refinery/ui/source/js/data-set-import/controllers/isa-tab-import.js
  refinery/ui/source/js/data-set-import/controllers/isa-tab-import.spec.js
  refinery/ui/source/js/data-set-import/controllers/metadata-table.js
  refinery/ui/source/js/data-set-import/controllers/metadata-table.spec.js
  refinery/ui/source/js/data-set-import/directives/import-confirmation-modal.js
  refinery/ui/source/js/data-set-import/partials/dialog-list-confirmation.html
  refinery/ui/source/js/data-set-import/partials/import-confirmation-modal.html
  refinery/ui/source/js/data-set-import/partials/isa-tab-import.html
  refinery/ui/source/js/data-set-import/partials/metadata-table.html
  refinery/ui/source/js/data-set-import/services/file-sources.js
Labels: HSCI requested feature, dataset, fix-8x-large, metadata, server, ui

#2852 Scottx611x/reintroduce pending import state
  refinery/data_set_manager/search_indexes.py
  refinery/data_set_manager/tests.py
Labels: files, fix-1x-quick, import, server, solr

#2788 Make the EC2 Instant Type configurable
  deployment/aws-config/config.yaml.erb
  deployment/stack.py
  deployment/utils.py
Labels: aws, deployment, enhancement, fix-2x-small

#2871 Properly create `Attribute` instances within factory boy utils
  refinery/factory_boy/utils.py
Labels: bug, fix-1x-quick, solr

#2885 Scottx611x/fix 2872
  refinery/tool_manager/models.py
  refinery/tool_manager/tests.py
Labels: events, fix-1x-quick, server, tools

#2890 Scottx611x/fix add file source translation
  refinery/core/models.py
  refinery/data_set_manager/test_views.py
  refinery/data_set_manager/views.py
  refinery/ui/source/js/data-set-import/controllers/file-upload-s3.js
Labels: aws, bug, dataset, files, server
