Repository refinery-platform/refinery-platform, pull requests merged in 2018-04, with the labels that each got.

#2712 Fix BAM index file generation
  refinery/core/serializers.py
  refinery/core/tests.py
  refinery/data_set_manager/tasks.py
  refinery/file_store/models.py
Labels: analysis, bug, core, files, fix-1x-quick, important, server

#2714 Remove the last remaining parts of the file_server Django app
  refinery/config/settings/base.py
  refinery/file_server/__init__.py
  refinery/file_server/migrations/0001_initial.py
  refinery/file_server/migrations/0002_final.py
  refinery/file_server/migrations/__init__.py
  refinery/file_server/models.py
Labels: files, fix-1x-quick, server, technical debt

#2715 Remove NodeManager class and related items
  refinery/data_set_manager/genomes.py
  refinery/data_set_manager/models.py
Labels: dataset, fix-1x-quick, metadata, server, technical debt

#2724 Remove unused django-resumable Python module
  requirements.txt
Labels: deployment, fix-1x-quick, server, technical debt

#2723 File import bug fixes
  refinery/config/settings/base.py
  refinery/core/models.py
  refinery/core/tests.py
  refinery/data_set_manager/search_indexes.py
  refinery/data_set_manager/tests.py
  refinery/data_set_manager/views.py
  refinery/file_store/models.py
  refinery/file_store/tasks.py
  refinery/file_store/test_models.py
Labels: bug, celery, files, fix-8x-large, import, server

#2730 Jkmarx/fix vis ui
  refinery/ui/source/js/data-set-visualization/ctrls/visualization-ctrl.js
  refinery/ui/source/js/data-set-visualization/partials/visualization.html
  refinery/ui/source/js/data-set-visualization/services/visualization.js
  refinery/ui/source/js/tool-launch/ctrls/tool-launch-button-ctrl.js
Labels: bug, ui

#2733 Escape @ symbol to fix filter bug.
  refinery/data_set_manager/utils.py
Labels: bug
