Repository refinery-platform/refinery-platform, pull requests merged in 2018-03, with the labels that each got.

#2634 Hackdna/refactor file store
  refinery/analysis_manager/tasks.py
  refinery/core/models.py
  refinery/core/test_utils.py
  refinery/core/utils.py
  refinery/data_set_manager/isa_tab_parser.py
  refinery/data_set_manager/models.py
  refinery/data_set_manager/search_indexes.py
  refinery/data_set_manager/tasks.py
  refinery/data_set_manager/tests.py
  refinery/data_set_manager/utils.py
  refinery/data_set_manager/views.py
  refinery/file_store/admin.py
  refinery/file_store/migrations/0008_auto_20180226_1110.py
  refinery/file_store/models.py
  refinery/file_store/tasks.py
  refinery/file_store/tests.py
  refinery/user_files_manager/tests.py
Labels: files, fix-8x-large, server, technical debt, tests

#2635 Remove Python package bitstring
  requirements.txt
Labels: deployment, fix-1x-quick, server, technical debt

#2651 Refactor file_store tests and models into separate files
  refinery/config/settings/aws.py
  refinery/config/settings/base.py
  refinery/file_store/migrations/0001_initial.py
  refinery/file_store/models.py
  refinery/file_store/test_models.py
  refinery/file_store/test_utils.py
  refinery/file_store/test_views.py
  refinery/file_store/utils.py
Labels: files, fix-2x-small, server, technical debt

#2657 Hackdna/delete files
  refinery/file_store/models.py
  refinery/file_store/tasks.py
  refinery/file_store/test_models.py
  requirements.txt
Labels: bug, files, fix-4x-medium, server, tests

#2648 Hackdna/update fabfile
  fabfile.py
Labels: deployment, fix-1x-quick, technical debt

#2659 Update user/files to view datasets with read_all plus perms.
  refinery/user_files_manager/utils.py
Labels: bug

#2664 Hackdna/remove create task
  refinery/analysis_manager/tasks.py
  refinery/core/tasks.py
  refinery/data_set_manager/isa_tab_parser.py
  refinery/data_set_manager/single_file_column_parser.py
  refinery/file_store/models.py
  refinery/file_store/tasks.py
  refinery/file_store/test_models.py
Labels: analysis, core, dataset, files, fix-4x-medium, import, server, technical debt

#2646 Scottx611x/delete related Dataset & Analysis objects
  .isort.cfg
  refinery/analysis_manager/tests.py
  refinery/core/api.py
  refinery/core/models.py
  refinery/core/tests.py
  refinery/core/views.py
  refinery/data_set_manager/models.py
  refinery/data_set_manager/tests.py
  refinery/data_set_manager/views.py
  refinery/factory_boy/django_model_factories.py
  refinery/factory_boy/utils.py
Labels: fix-4x-medium

#2671 Replace DownloadError with RuntimeError
  refinery/data_set_manager/views.py
  refinery/file_store/tasks.py
Labels: files, fix-1x-quick, server, technical debt

#2672 Hackdna/update apache config
  deployment/refinery-modules/refinery/manifests/apache2.pp
  deployment/stack.py
Labels: aws, deployment, enhancement, fix-2x-small, server

#2683 Remove upload_bucket_name output from root and bucket_name_base outpu…
  deployment/terraform/live/main.tf
  deployment/terraform/live/outputs.tf
  deployment/terraform/modules/s3/outputs.tf
Labels: cloud, deployment, fix-1x-quick, technical debt

#2656 Scottx611x/Add VPC to Terraform
  deployment/aws-config/config.yaml.erb
  deployment/stack.py
  deployment/terraform/README.md
  deployment/terraform/live/main.tf
  deployment/terraform/live/outputs.tf
  deployment/terraform/live/terraform.tfvars.template
  deployment/terraform/live/vars.tf
  deployment/terraform/modules/rds/main.tf
  deployment/terraform/modules/rds/outputs.tf
  deployment/terraform/modules/rds/vars.tf
  deployment/terraform/modules/s3/vars.tf
  deployment/terraform/modules/vpc/main.tf
  deployment/terraform/modules/vpc/outputs.tf
  deployment/terraform/modules/vpc/vars.tf
  refinery/config/settings/aws.py
Labels: fix-8x-large

#2682 Hide button for owners.
  refinery/data_set_manager/urls.py
  refinery/data_set_manager/views.py
  refinery/ui/source/js/data-set-about/ctrls/details-ctrl.js
  refinery/ui/source/js/data-set-about/partials/details.html
Labels: bug, ui

#2695 Fix perms to allow modify_perm users to view workflows.
  refinery/tool_manager/views.py
Labels: bug
