Repository refinery-platform/refinery-platform, pull requests merged in 2018-02, with the labels that each got.

#2594 Keep chunked uploads outside file_store dir and delete chunked upload…
  refinery/config/settings/base.py
  refinery/data_set_manager/views.py
Labels: enhancement, files, fix-2x-small, import, server

#2599 Remove DiskQuota model
  refinery/core/admin.py
  refinery/core/migrations/0017_delete_diskquota.py
  refinery/core/models.py
Labels: core, files, fix-1x-quick, server, technical debt

#2601 Fix form alignment.
  refinery/ui/source/js/data-set-about/partials/details.html
Labels: bug
