Repository refinery-platform/refinery-platform, pull requests merged in 2019-07, with the labels that each got.

#3410 Upgrade bower for critical update.
  .travis.yml
  deployment/puppet/refinery/manifests/ui.pp
Labels: important, ui

#3401 Display the tools display name for analysis model.
  refinery/core/serializers.py
  refinery/ui/source/js/analysis-monitor/partials/analyses-list.html
  refinery/ui/source/js/analysis-monitor/partials/global-status-popover.html
Labels: bug, ui

#3414 Downgrade django-storages
  requirements.txt
Labels: aws, deployment, server, technical debt

#3417 Fix data set edit bug.
  refinery/ui/source/js/data-set-about/ctrls/details-ctrl.js
Labels: bug, ui

#3418 Update UserProfile.uuid migrations to allow upgrading django_extensions
  refinery/core/migrations/0001_initial.py
  refinery/core/migrations/0033_userprofile_uuid.py
Labels: core, database, fix-2x-small, server, technical debt

#3419 Fix UUIDField migrations in AnalysisStatus to allow upgrading django_extensions
  refinery/analysis_manager/migrations/0001_initial.py
  refinery/analysis_manager/migrations/0003_auto_20170726_1601.py
  refinery/analysis_manager/migrations/0004_auto_20171211_1145.py
  refinery/analysis_manager/migrations/0005_analysisstatus_refinery_import_task_group_id.py
  refinery/analysis_manager/migrations/0006_analysisstatus_galaxy_import_task_group_id.py
  refinery/analysis_manager/migrations/0007_analysisstatus_galaxy_export_task_group_id.py
  refinery/analysis_manager/migrations/0008_analysisstatus_galaxy_workflow_task_group_id.py
Labels: analysis, database, fix-2x-small, server, technical debt

#3421 Migrate UUIDField token_uuid in Invitation model
  refinery/core/migrations/0001_initial.py
  refinery/core/migrations/0034_invitation_token_uuid.py
  refinery/core/models.py
  refinery/core/test_serializers.py
  refinery/core/test_views.py
Labels: core, database, fix-2x-small, server, technical debt

#3425 Fix padding
  refinery/ui/source/js/analysis-monitor/partials/analyses-list.html
  refinery/ui/source/js/data-set-about/partials/details.html
  refinery/ui/source/js/tool-launch/partials/input-group.html
Labels: bug, ui

#3422 Delete stale content types
  refinery/core/migrations/0017_delete_diskquota.py
  refinery/core/migrations/0018_auto_20180306_1333.py
  refinery/core/migrations/0032_delete_ontology.py
  refinery/data_set_manager/migrations/0007_remove_attribute_definition.py
Labels: core, database, dataset, deployment, fix-2x-small, server, technical debt

#3424 Migrate UUIDField uuid in Parameter model
  refinery/tool_manager/migrations/0001_initial.py
  refinery/tool_manager/migrations/0029_parameter_uuid.py
  refinery/tool_manager/models.py
  refinery/tool_manager/tests.py
Labels: database, fix-2x-small, server, technical debt, tools

#3416 Migrate UUIDField uuid in Assay model
  refinery/data_set_manager/migrations/0001_initial.py
  refinery/data_set_manager/migrations/0008_assay_uuid.py
  refinery/data_set_manager/models.py
  refinery/data_set_manager/test_views.py
  refinery/data_set_manager/tests.py
  refinery/data_set_manager/utils.py
  refinery/data_set_manager/views.py
  refinery/user_files_manager/utils.py
Labels: database, dataset, fix-4x-medium, server, technical debt

#3426 Jkmarx/move dependencies to npm
  .gitignore
  .travis.yml
  deployment/puppet/refinery/manifests/ui.pp
  fabfile.py
  refinery/config/settings/base.py
  refinery/templates/base.html
  refinery/templates/core/data_set.html
  refinery/templates/data_set_manager/import.html
  refinery/ui/.bowerrc
  refinery/ui/.eslintignore
  refinery/ui/Gruntfile.js
  refinery/ui/bower.json
  refinery/ui/config.json
  refinery/ui/package.json
  refinery/ui/source/js/data-set-import/module.js
  refinery/ui/source/js/file-browser/module.js
  refinery/ui/source/styles/dashboard.less
  refinery/ui/source/styles/home.less
  refinery/ui/source/styles/refinery-style-bootstrap-responsive.less
  refinery/ui/source/styles/refinery-style-bootstrap.less
  refinery/ui/source/styles/refinery-style.less
Labels: technical debt

#3428 Fail fast on Travis when running Django tests
  .travis.yml
Labels: enhancement, fix-1x-quick, server, tests, travis-ci

#3427 Migrate UUIDField analysis_uuid in AnalysisResult
  refinery/analysis_manager/tasks.py
  refinery/core/admin.py
  refinery/core/migrations/0001_initial.py
  refinery/core/migrations/0035_update_analysisresult_analysis_uuid.py
  refinery/core/migrations/0036_migrate_analysisresult_analysis_uuid.py
  refinery/core/migrations/0037_remove_analysisresult_analysis_uuid.py
  refinery/core/models.py
  refinery/core/test_models.py
  refinery/core/test_views.py
  refinery/factory_boy/utils.py
  refinery/tool_manager/tests.py
Labels: analysis, core, database, fix-8x-large, server, technical debt

#3411 Jkmarx/upgrade node js
  .gitignore
  .travis.yml
  deployment/puppet/Puppetfile
  deployment/puppet/Puppetfile.lock
  deployment/puppet/refinery/manifests/ui.pp
  fabfile.py
  refinery/config/settings/base.py
  refinery/templates/base.html
  refinery/templates/core/data_set.html
  refinery/templates/data_set_manager/import.html
  refinery/ui/.bowerrc
  refinery/ui/.eslintignore
  refinery/ui/.eslintrc
  refinery/ui/Gruntfile.js
  refinery/ui/bower.json
  refinery/ui/config.json
  refinery/ui/cypress.json
  refinery/ui/karma.config.js
  refinery/ui/package.json
  refinery/ui/source/js/data-set-import/module.js
  refinery/ui/source/js/file-browser/module.js
  refinery/ui/source/styles/dashboard.less
  refinery/ui/source/styles/home.less
  refinery/ui/source/styles/refinery-style-bootstrap-responsive.less
  refinery/ui/source/styles/refinery-style-bootstrap.less
  refinery/ui/source/styles/refinery-style.less
Labels: technical debt, ui
