Repository refinery-platform/refinery-platform, pull requests merged in 2019-05, with the labels that each got.

#3361 Improve error handling during ISA-Tab parsing
  CHANGELOG.md
  refinery/data_set_manager/tasks.py
  version.txt
Labels: aws, dataset, fix-2x-small, import, metadata, server, technical debt

#3362 Jkmarx/import hide confirm button
  refinery/ui/source/js/data-set-import/partials/file-upload-command-line-modal.html
  refinery/ui/source/js/data-set-import/partials/isa-tab-import.html
  refinery/ui/source/js/data-set-import/partials/metadata-table.html
Labels: bug, ui

#3364 Jkmarx/fix collaboration incorrect param
  refinery/ui/source/js/commons/ctrls/group-member-edit-modal-ctrl.js
  refinery/ui/source/js/commons/services/group-member.spec.js
  refinery/ui/source/js/dashboard/controllers/dashboard-main-ctrl.js
Labels: bug

#3367 Remove unused GroupManagement and UserAuthentication classes
  refinery/core/models.py
Labels: core, fix-1x-quick, server, technical debt

#3371 Jkmarx/fix command line bugs
  refinery/ui/source/js/dashboard/partials/data-sets-card.html
  refinery/ui/source/js/data-set-import/controllers/file-upload-command-line-modal-ctrl.js
  refinery/ui/source/js/data-set-import/partials/file-upload-command-line-modal.html
Labels: bug

#3369 Jkmarx/fix routing issue for demoting users
  refinery/core/test_views.py
  refinery/core/urls.py
  refinery/core/views.py
  refinery/ui/source/js/commons/ctrls/group-edit-modal-ctrl.js
  refinery/ui/source/js/commons/ctrls/group-edit-modal-ctrl.spec.js
  refinery/ui/source/js/commons/ctrls/group-member-edit-modal-ctrl.js
  refinery/ui/source/js/commons/ctrls/group-member-edit-modal-ctrl.spec.js
  refinery/ui/source/js/commons/partials/group-member-edit-modal.html
  refinery/ui/source/js/commons/services/group-member.js
  refinery/ui/source/js/commons/services/group-member.spec.js
  refinery/ui/source/js/dashboard/controllers/collaboration-card-ctrl.spec.js
  refinery/ui/source/js/data-set-about/services/factory.js
Labels: bug, important, ui

#3375 Fix typo.
  refinery/ui/source/js/data-set-import/controllers/file-upload-command-line-modal-ctrl.js
Labels: bug, ui

#3376 Fix missing text on the s3 file upload page.
  refinery/ui/source/js/data-set-import/partials/file-upload-s3.html
Labels: bug, ui

#3377 Jkmarx/fix upload text for clarity
  refinery/ui/source/js/data-set-import/partials/file-upload-s3.html
  refinery/ui/source/js/data-set-import/partials/isa-tab-import.html
  refinery/ui/source/js/data-set-import/partials/metadata-table.html
Labels: bug, ui

#3368 Replace a custom noop with RunPython.noop in database migrations
  refinery/core/migrations/0016_update_read_meta_permissions.py
  refinery/core/migrations/0020_create_initial_site_statistics.py
  refinery/data_set_manager/migrations/0005_update_attribute_orders.py
Labels: database, fix-1x-quick, server, technical debt

#3378 Hackdna/update upload box
  refinery/ui/source/js/data-set-import/partials/file-upload-command-line-modal.html
Labels: aws, client, enhancement, files, fix-1x-quick, import, ui

#3381 Jkmarx/finish api view names update
  refinery/data_set_manager/test_views.py
  refinery/data_set_manager/urls.py
  refinery/data_set_manager/views.py
  refinery/file_store/test_views.py
  refinery/file_store/urls.py
  refinery/file_store/views.py
  refinery/user_files_manager/tests.py
  refinery/user_files_manager/urls.py
  refinery/user_files_manager/views.py
Labels: api, technical debt

#3380 Jkmarx/correct core api view names
  refinery/core/test_views.py
  refinery/core/urls.py
  refinery/core/views.py
  refinery/data_set_manager/test_views.py
  refinery/data_set_manager/urls.py
  refinery/data_set_manager/views.py
  refinery/file_store/test_views.py
  refinery/file_store/urls.py
  refinery/file_store/views.py
  refinery/user_files_manager/tests.py
  refinery/user_files_manager/urls.py
  refinery/user_files_manager/views.py
Labels: api, technical debt

#3382 Hide attributes related to downloading files.
  refinery/data_set_manager/models.py
  refinery/data_set_manager/views.py
Labels: bug

#3385 Raise faker module log level to INFO to avoid spurious messages
  refinery/config/settings/base.py
Labels: fix-1x-quick, server, technical debt

#3384 Update UUIDField in UserProfile model
  refinery/core/migrations/0033_userprofile_uuid.py
  refinery/core/models.py
  refinery/core/serializers.py
  refinery/core/test_views.py
  refinery/core/views.py
  refinery/tool_manager/models.py
  refinery/tool_manager/tests.py
Labels: core, database, fix-8x-large, server, technical debt

#3390 Fix Cypress error on Travis CI
  .travis.yml
Labels: deployment, fix-1x-quick, important, technical debt, tests, travis-ci

#3389 Migrate UUIDField refinery_import_task_id in AnalysisStatus model
  refinery/analysis_manager/migrations/0005_analysisstatus_refinery_import_task_group_id.py
  refinery/analysis_manager/models.py
Labels: analysis, database, fix-2x-small, server, technical debt
