Repository refinery-platform/refinery-platform, pull requests merged in 2019-04, with the labels that each got.

#3303 Avoid unneccessary api call.
  refinery/ui/source/js/dashboard/controllers/dashboard-main-ctrl.js
Labels: bug, ui

#3301 Jkmarx/extend group api to delete
  refinery/core/test_views.py
  refinery/core/views.py
Labels: api, technical debt

#3302 Jkmarx/update client with group api enhancements
  refinery/core/serializers.py
  refinery/core/test_views.py
  refinery/core/views.py
  refinery/ui/source/js/commons/ctrls/group-add-modal-ctrl.js
  refinery/ui/source/js/commons/ctrls/group-add-modal-ctrl.spec.js
  refinery/ui/source/js/commons/ctrls/group-edit-modal-ctrl.js
  refinery/ui/source/js/commons/ctrls/group-edit-modal-ctrl.spec.js
  refinery/ui/source/js/commons/services/group-extended.js
  refinery/ui/source/js/commons/services/group.spec.js
  refinery/ui/source/js/dashboard/controllers/dashboard-main-ctrl.js
  refinery/ui/source/js/dashboard/controllers/dashboard-main-ctrl.spec.js
  refinery/ui/source/js/dashboard/directives/collaboration-card.spec.js
  refinery/ui/source/js/dashboard/directives/dashboard.spec.js
  refinery/ui/source/js/dashboard/directives/data-sets-card.spec.js
  refinery/ui/source/js/dashboard/directives/history-card.spec.js
  refinery/ui/source/js/dashboard/directives/primary-group-button.spec.js
Labels: api, technical debt, ui

#3300 Jkmarx/extend group api return all user groups
  refinery/core/serializers.py
  refinery/core/test_views.py
  refinery/core/views.py
  refinery/ui/source/js/commons/ctrls/group-add-modal-ctrl.js
  refinery/ui/source/js/commons/ctrls/group-add-modal-ctrl.spec.js
  refinery/ui/source/js/commons/ctrls/group-edit-modal-ctrl.js
  refinery/ui/source/js/commons/ctrls/group-edit-modal-ctrl.spec.js
  refinery/ui/source/js/commons/services/group-extended.js
  refinery/ui/source/js/commons/services/group.spec.js
  refinery/ui/source/js/dashboard/controllers/dashboard-main-ctrl.js
  refinery/ui/source/js/dashboard/controllers/dashboard-main-ctrl.spec.js
  refinery/ui/source/js/dashboard/directives/collaboration-card.spec.js
  refinery/ui/source/js/dashboard/directives/dashboard.spec.js
  refinery/ui/source/js/dashboard/directives/data-sets-card.spec.js
  refinery/ui/source/js/dashboard/directives/history-card.spec.js
  refinery/ui/source/js/dashboard/directives/primary-group-button.spec.js
Labels: api, technical debt

#3304 Hackdna/postgresql update
  deployment/puppet/manifests/site.pp
  deployment/puppet/refinery/manifests/postgresql.pp
  deployment/puppet/refinery/manifests/python.pp
  deployment/terraform/modules/rds/main.tf
Labels: aws, database, deployment, fix-4x-medium, technical debt

#3311 Remove unused group api v1 resource.
  refinery/config/urls.py
  refinery/core/api.py
Labels: api, technical debt

#3310 Update client to group memebers api v2.
  refinery/config/urls.py
  refinery/core/api.py
  refinery/ui/source/js/commons/ctrls/group-edit-modal-ctrl.js
  refinery/ui/source/js/commons/ctrls/group-member-edit-modal-ctrl.js
  refinery/ui/source/js/commons/services/group-member.js
  refinery/ui/source/js/commons/services/group-member.spec.js
Labels: technical debt, ui

#3309 Jkmarx/add group member api
  refinery/config/urls.py
  refinery/core/api.py
  refinery/core/models.py
  refinery/core/serializers.py
  refinery/core/test_models.py
  refinery/core/test_views.py
  refinery/core/urls.py
  refinery/core/views.py
  refinery/ui/source/js/commons/ctrls/group-edit-modal-ctrl.js
  refinery/ui/source/js/commons/ctrls/group-member-edit-modal-ctrl.js
  refinery/ui/source/js/commons/services/group-member.js
  refinery/ui/source/js/commons/services/group-member.spec.js
Labels: api, technical debt

#3312 Raise error when user object is not found.
  refinery/user_files_manager/utils.py
Labels: api, bug

#3318 Remove tasty pie.
  refinery/config/settings/base.py
  refinery/config/urls.py
  refinery/core/api.py
  refinery/core/test_api.py
  requirements.txt
Labels: api, technical debt

#3317 Jkmarx/update client to invite api v2
  refinery/config/settings/base.py
  refinery/config/urls.py
  refinery/core/api.py
  refinery/core/test_api.py
  refinery/ui/source/js/commons/ctrls/group-member-add-modal-ctrl.js
  refinery/ui/source/js/commons/services/group-invite.js
  refinery/ui/source/js/commons/services/group-invite.spec.js
  refinery/ui/source/js/dashboard/controllers/collaboration-card-ctrl.js
  refinery/ui/source/js/dashboard/controllers/dashboard-main-ctrl.js
  refinery/ui/source/js/dashboard/partials/collaboration-card.html
  requirements.txt
Labels: technical debt, ui

#3316 Add get_group helper method.
  refinery/config/settings/base.py
  refinery/config/urls.py
  refinery/core/api.py
  refinery/core/test_api.py
  refinery/core/test_utils.py
  refinery/core/utils.py
  refinery/core/views.py
  refinery/ui/source/js/commons/ctrls/group-member-add-modal-ctrl.js
  refinery/ui/source/js/commons/services/group-invite.js
  refinery/ui/source/js/commons/services/group-invite.spec.js
  refinery/ui/source/js/dashboard/controllers/collaboration-card-ctrl.js
  refinery/ui/source/js/dashboard/controllers/dashboard-main-ctrl.js
  refinery/ui/source/js/dashboard/partials/collaboration-card.html
  requirements.txt
Labels: api, technical debt

#3314 Jkmarx/create group invitations api
  refinery/config/settings/base.py
  refinery/config/urls.py
  refinery/core/api.py
  refinery/core/serializers.py
  refinery/core/test_api.py
  refinery/core/test_serializers.py
  refinery/core/test_utils.py
  refinery/core/test_views.py
  refinery/core/urls.py
  refinery/core/utils.py
  refinery/core/views.py
  refinery/ui/source/js/commons/ctrls/group-member-add-modal-ctrl.js
  refinery/ui/source/js/commons/services/group-invite.js
  refinery/ui/source/js/commons/services/group-invite.spec.js
  refinery/ui/source/js/dashboard/controllers/collaboration-card-ctrl.js
  refinery/ui/source/js/dashboard/controllers/dashboard-main-ctrl.js
  refinery/ui/source/js/dashboard/partials/collaboration-card.html
  requirements.txt
Labels: api, technical debt

#3321 Add label stying to prevent label hiding.
  refinery/ui/source/js/home/partials/data-set-chart.html
  refinery/ui/source/styles/home.less
Labels: bug, ui

#3323 Fix bug with incorrect logic.
  refinery/ui/source/js/tool-launch/ctrls/tool-launch-button-ctrl.js
  refinery/ui/source/js/tool-launch/ctrls/tool-launch-button-ctrl.spec.js
Labels: bug, ui

#3322 Upgrade Supervisor to version 4.0.0
  requirements.txt
Labels: deployment, fix-2x-small, server, technical debt

#3327 Hackdna/celery upgrade
  refinery/supervisord.conf.erb
  requirements.txt
Labels: celery, deployment, fix-4x-medium, server, technical debt

#3324 Remove swagger.
  .travis.yml
  refinery/config/settings/base.py
  refinery/config/urls.py
  refinery/core/utils.py
  requirements.txt
Labels: technical debt

#3325 Add missing serializer field to resolve ui bug.
  refinery/core/serializers.py
  refinery/core/test_serializers.py
  refinery/core/test_views.py
  refinery/ui/source/js/analysis-monitor/partials/analyses-list.html
Labels: api, bug, ui

#3328 Add comments to api for clarity.
  refinery/core/views.py
  refinery/data_set_manager/views.py
Labels: documentation, technical debt

#3330 Jkmarx/remove neo4j
  .travis.yml
  backup.sh
  deployment/puppet/manifests/site.pp
  deployment/puppet/refinery/manifests/init.pp
  deployment/puppet/refinery/manifests/neo4j.pp
  refinery/config/config.json.erb
  refinery/config/settings/base.py
  refinery/core/admin.py
  refinery/core/management/commands/clear_annotations.py
  refinery/core/management/commands/import_annotations.py
  refinery/core/management/commands/import_ontology.py
  refinery/core/migrations/0032_delete_ontology.py
  refinery/core/models.py
  refinery/core/test_models.py
  refinery/core/tests.py
  refinery/core/urls.py
  refinery/core/utils.py
  refinery/core/views.py
  refinery/data_set_manager/tasks.py
  refinery/ui/cypress/integration/logged_in/visualization_spec.js
  refinery/ui/source/js/dashboard/partials/file-browser-disabled.html
  refinery/ui/source/js/dashboard/services/search-api.js
  refinery/ui/source/js/dashboard/services/search-api.spec.js
  refinery/ui/source/js/refinery-settings.js
  requirements.txt
  restore.sh
Labels: server, technical debt

#3331 Remove amqplib and upgrade librabbitmq to version 2.0.0
  requirements.txt
Labels: celery, deployment, fix-1x-quick, server, technical debt

#3332 Jkmarx/remove solr synonyms setting
  .gitignore
  deployment/puppet/refinery/manifests/params.pp
  deployment/puppet/refinery/manifests/solr.pp
  refinery/config/config.json.erb
  refinery/config/settings/base.py
  refinery/core/context_processors.py
  refinery/core/management/commands/install_solr_synonym_plugin.py
  refinery/core/management/commands/solr_synonyms.py
  refinery/core/management/commands/uninstall_solr_synonym_plugin.py
  refinery/solr/core/conf/solrconfig.xml.erb
  refinery/solr/solr.xml
  refinery/templates/base.html
  refinery/ui/cypress/fixtures/neo4j-annotations.json
  refinery/ui/cypress/fixtures/solr_co.json
  refinery/ui/source/js/dashboard/services/search-api.js
  refinery/ui/source/js/dashboard/services/search-api.spec.js
Labels: server, solr, technical debt, ui

#3334 Update Django-related packages in preparation for v1.9 upgrade
  refinery/config/settings/djdt.py
  requirements.txt
Labels: deployment, fix-2x-small, server, technical debt

#3335 Jkmarx/refactor viewset names
  refinery/core/test_views.py
  refinery/core/urls.py
  refinery/core/views.py
  refinery/data_set_manager/test_views.py
  refinery/data_set_manager/urls.py
  refinery/data_set_manager/views.py
Labels: api, technical debt

#3336 Add unit tests.
  refinery/ui/source/js/data-set-import/controllers/file-upload-command-line-button-ctrl.spec.js
  refinery/ui/source/js/data-set-import/controllers/file-upload-command-line-modal-ctrl.js
  refinery/ui/source/js/data-set-import/controllers/file-upload-command-line-modal-ctrl.spec.js
  refinery/ui/source/js/data-set-import/directives/file-upload-command-line-button.spec.js
  refinery/ui/source/js/data-set-import/directives/file-upload-command-line-modal.spec.js
Labels: ui

#3339 Update params per style guide.
  refinery/data_set_manager/test_views.py
  refinery/data_set_manager/views.py
  refinery/ui/source/js/commons/services/studies.js
  refinery/ui/source/js/commons/services/studies.spec.js
  refinery/ui/source/js/data-set-about/services/factory.js
  refinery/ui/source/js/provvis/ctrls/ctrl.js
Labels: technical debt

#3340 Fix hiding of buttons on resize.
  refinery/ui/source/js/data-set-about/partials/details.html
Labels: bug, ui

#3337 Update to match style guide for params for analysis view set
  refinery/core/test_views.py
  refinery/core/views.py
  refinery/ui/source/js/analysis-monitor/ctrls/ctrl.js
  refinery/ui/source/js/analysis-monitor/services/factory.js
  refinery/ui/source/js/commons/services/analyses.spec.js
  refinery/ui/source/js/provvis/ctrls/ctrl.js
Labels: api, technical debt

#3294 Add components to launch download script modal.
  refinery/ui/source/js/data-set-import/controllers/file-upload-command-line-button-ctrl.js
  refinery/ui/source/js/data-set-import/controllers/file-upload-command-line-button-ctrl.spec.js
  refinery/ui/source/js/data-set-import/controllers/file-upload-command-line-modal-ctrl.js
  refinery/ui/source/js/data-set-import/controllers/file-upload-command-line-modal-ctrl.spec.js
  refinery/ui/source/js/data-set-import/controllers/isa-tab-import.js
  refinery/ui/source/js/data-set-import/controllers/metadata-table.js
  refinery/ui/source/js/data-set-import/directives/file-upload-command-line-button.js
  refinery/ui/source/js/data-set-import/directives/file-upload-command-line-button.spec.js
  refinery/ui/source/js/data-set-import/directives/file-upload-command-line-modal.js
  refinery/ui/source/js/data-set-import/directives/file-upload-command-line-modal.spec.js
  refinery/ui/source/js/data-set-import/directives/isa-tab-import.js
  refinery/ui/source/js/data-set-import/directives/isa-tab-import.spec.js
  refinery/ui/source/js/data-set-import/partials/file-upload-command-line-button.html
  refinery/ui/source/js/data-set-import/partials/file-upload-command-line-modal.html
  refinery/ui/source/js/data-set-import/partials/file-upload-s3.html
  refinery/ui/source/js/data-set-import/partials/file-upload.html
  refinery/ui/source/js/data-set-import/partials/isa-tab-import.html
  refinery/ui/source/js/data-set-import/partials/metadata-table.html
  refinery/ui/source/js/data-set-import/views/isa-tab-import.html
  refinery/ui/source/js/refinery-libraries.js
  refinery/ui/source/styles/refinery-style.less
Labels: enhancement, import, ui

#3338 Jkmarx/update group view set params
  refinery/core/test_views.py
  refinery/core/views.py
  refinery/data_set_manager/test_views.py
  refinery/data_set_manager/views.py
  refinery/ui/source/js/commons/ctrls/permission-editor-ctrl.js
  refinery/ui/source/js/commons/services/group.spec.js
  refinery/ui/source/js/commons/services/studies.js
  refinery/ui/source/js/commons/services/studies.spec.js
  refinery/ui/source/js/dashboard/services/permission.js
  refinery/ui/source/js/data-set-about/directives/group-perms.spec.js
  refinery/ui/source/js/data-set-about/services/factory.js
  refinery/ui/source/js/file-browser/services/data-set-group-perms-service.js
  refinery/ui/source/js/file-browser/services/data-set-group-perms-service.spec.js
  refinery/ui/source/js/provvis/ctrls/ctrl.js
Labels: technical debt

#3343 Fix missing delete analysis button.
  refinery/ui/source/js/analysis-monitor/ctrls/ctrl.js
  refinery/ui/source/js/analysis-monitor/ctrls/ctrl.spec.js
  refinery/ui/source/js/analysis-monitor/partials/analyses-list.html
Labels: bug, ui

#3344 Resolve loading error.
  refinery/ui/config.json
Labels: bug, ui

#3341 Hackdna/update urls
  refinery/analysis_manager/urls.py
  refinery/annotation_server/urls.py
  refinery/config/urls.py
  refinery/core/urls.py
  refinery/data_set_manager/urls.py
  refinery/tool_manager/urls.py
  refinery/user_files_manager/urls.py
Labels: fix-8x-large, server, technical debt

#3346 Fix bug due to missing lookup field.
  refinery/data_set_manager/views.py
Labels: api, bug

#3349 Fix text which shouldn't be shown.
  refinery/ui/source/js/data-set-about/partials/details.html
Labels: bug, ui

#3347 Fix missing cancel button.
  refinery/ui/source/js/analysis-monitor/partials/analyses-list.html
Labels: bug, ui

#3348 Hackdna/update api urls
  refinery/config/urls.py
  refinery/config/utils.py
  refinery/core/urls.py
  refinery/data_set_manager/urls.py
  refinery/file_store/urls.py
  refinery/tool_manager/urls.py
  refinery/user_files_manager/urls.py
Labels: api, fix-4x-medium, server, technical debt

#3350 Add missing serializer fields.
  refinery/core/serializers.py
  refinery/core/test_serializers.py
  refinery/core/test_views.py
  refinery/core/views.py
  refinery/ui/source/js/data-set-about/ctrls/details-ctrl.js
  refinery/ui/source/js/data-set-about/partials/details.html
  refinery/ui/source/js/data-set-about/services/factory.spec.js
  refinery/ui/source/js/file-browser/views/files-tab.html
Labels: api, bug

#3353 Fix close button position.
  refinery/ui/source/styles/dashboard.less
Labels: bug, ui

#3354 Add missing context.
  refinery/core/views.py
Labels: api, bug

#3355 Fix bug due to incorrect reference.
  refinery/ui/source/js/dashboard/partials/collaboration-card.html
Labels: bug, ui

#3356 Fix incorrect field reference.
  refinery/ui/source/js/data-set-about/partials/group-perms.html
Labels: bug, ui
